# Form implementation generated from reading ui file 'src/my_pyqt_app/ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BilibiliRankWindow(object):
    def setupUi(self, BilibiliRankWindow):
        BilibiliRankWindow.setObjectName("BilibiliRankWindow")
        BilibiliRankWindow.resize(900, 700)
        BilibiliRankWindow.setStyleSheet("QWidget { background-color: #f5f5f5; font-family: \"Microsoft YaHei\", sans-serif; }")
        self.verticalLayout = QtWidgets.QVBoxLayout(BilibiliRankWindow)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleWidget = QtWidgets.QWidget(parent=BilibiliRankWindow)
        self.titleWidget.setObjectName("titleWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(parent=self.titleWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: #333333;")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.questionMark = QtWidgets.QLabel(parent=self.titleWidget)
        self.questionMark.setStyleSheet("color: #ff3860; font-size: 24px; font-weight: bold; margin-left: 5px;")
        self.questionMark.setObjectName("questionMark")
        self.horizontalLayout_2.addWidget(self.questionMark)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.titleWidget)
        self.tabWidget = QtWidgets.QWidget(parent=BilibiliRankWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.dailyButton = QtWidgets.QPushButton(parent=self.tabWidget)
        self.dailyButton.setStyleSheet("QPushButton {\n"
"    color: #00a1d6; \n"
"    font-size: 16px; \n"
"    font-weight: bold;\n"
"    text-decoration: underline;\n"
"    background: transparent; \n"
"    border: none;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #0090c0;\n"
"}")
        self.dailyButton.setObjectName("dailyButton")
        self.horizontalLayout.addWidget(self.dailyButton)
        self.separator1 = QtWidgets.QLabel(parent=self.tabWidget)
        self.separator1.setStyleSheet("color: #cccccc; font-size: 16px; margin: 0 5px;")
        self.separator1.setObjectName("separator1")
        self.horizontalLayout.addWidget(self.separator1)
        self.weeklyButton = QtWidgets.QPushButton(parent=self.tabWidget)
        self.weeklyButton.setStyleSheet("QPushButton {\n"
"    color: #666666; \n"
"    font-size: 16px; \n"
"    background: transparent; \n"
"    border: none;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #00a1d6;\n"
"    text-decoration: underline;\n"
"}")
        self.weeklyButton.setObjectName("weeklyButton")
        self.horizontalLayout.addWidget(self.weeklyButton)
        self.separator2 = QtWidgets.QLabel(parent=self.tabWidget)
        self.separator2.setStyleSheet("color: #cccccc; font-size: 16px; margin: 0 5px;")
        self.separator2.setObjectName("separator2")
        self.horizontalLayout.addWidget(self.separator2)
        self.monthlyButton = QtWidgets.QPushButton(parent=self.tabWidget)
        self.monthlyButton.setStyleSheet("QPushButton {\n"
"    color: #666666; \n"
"    font-size: 16px; \n"
"    background: transparent; \n"
"    border: none;\n"
"    padding: 5px 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #00a1d6;\n"
"    text-decoration: underline;\n"
"}")
        self.monthlyButton.setObjectName("monthlyButton")
        self.horizontalLayout.addWidget(self.monthlyButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.tabWidget)
        self.infoWidget = QtWidgets.QWidget(parent=BilibiliRankWindow)
        self.infoWidget.setObjectName("infoWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.infoWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.updateLabel = QtWidgets.QLabel(parent=self.infoWidget)
        self.updateLabel.setStyleSheet("color: #666666; font-size: 12px;")
        self.updateLabel.setObjectName("updateLabel")
        self.horizontalLayout_3.addWidget(self.updateLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.countLabel = QtWidgets.QLabel(parent=self.infoWidget)
        self.countLabel.setStyleSheet("color: #666666; font-size: 12px;")
        self.countLabel.setObjectName("countLabel")
        self.horizontalLayout_3.addWidget(self.countLabel)
        self.verticalLayout.addWidget(self.infoWidget)
        self.progressBar = QtWidgets.QProgressBar(parent=BilibiliRankWindow)
        self.progressBar.setVisible(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    height: 10px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #00a1d6;\n"
"    border-radius: 3px;\n"
"}")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.tableWidget = QtWidgets.QTableWidget(parent=BilibiliRankWindow)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 6px;\n"
"    gridline-color: #f0f0f0;\n"
"    font-size: 13px;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid #f0f0f0;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #e6f7ff;\n"
"    color: #333333;  // 添加此行以保持文字颜色不变\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 2px solid #00a1d6;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"}")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.errorLabel = QtWidgets.QLabel(parent=BilibiliRankWindow)
        self.errorLabel.setVisible(False)
        self.errorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorLabel.setStyleSheet("QLabel {\n"
"    color: #ff6b6b;\n"
"    font-size: 14px;\n"
"    padding: 20px;\n"
"    background-color: #ffeaea;\n"
"    border: 1px solid #ffcccc;\n"
"    border-radius: 4px;\n"
"    margin: 10px 0px;\n"
"}")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.footerWidget = QtWidgets.QWidget(parent=BilibiliRankWindow)
        self.footerWidget.setObjectName("footerWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.footerWidget)
        self.horizontalLayout_4.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.refreshButton = QtWidgets.QPushButton(parent=self.footerWidget)
        self.refreshButton.setStyleSheet("QPushButton {\n"
"    background-color: #00a1d6;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0090c0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0080b0;\n"
"}")
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_4.addWidget(self.refreshButton)
        self.verticalLayout.addWidget(self.footerWidget)

        self.retranslateUi(BilibiliRankWindow)
        QtCore.QMetaObject.connectSlotsByName(BilibiliRankWindow)

    def retranslateUi(self, BilibiliRankWindow):
        _translate = QtCore.QCoreApplication.translate
        BilibiliRankWindow.setWindowTitle(_translate("BilibiliRankWindow", "B站问号榜"))
        self.titleLabel.setText(_translate("BilibiliRankWindow", "B站问号榜"))
        self.questionMark.setText(_translate("BilibiliRankWindow", "?"))
        self.dailyButton.setText(_translate("BilibiliRankWindow", "日榜"))
        self.separator1.setText(_translate("BilibiliRankWindow", "|"))
        self.weeklyButton.setText(_translate("BilibiliRankWindow", "周榜"))
        self.separator2.setText(_translate("BilibiliRankWindow", "|"))
        self.monthlyButton.setText(_translate("BilibiliRankWindow", "月榜"))
        self.updateLabel.setText(_translate("BilibiliRankWindow", "最后更新: 从未更新"))
        self.countLabel.setText(_translate("BilibiliRankWindow", "数据数量: 0"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BilibiliRankWindow", "排名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BilibiliRankWindow", "视频标题"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BilibiliRankWindow", "UP主"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BilibiliRankWindow", "播放量"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BilibiliRankWindow", "弹幕数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("BilibiliRankWindow", "点赞数"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("BilibiliRankWindow", "时长"))
        self.errorLabel.setText(_translate("BilibiliRankWindow", "获取排行榜失败，请检查网络连接后重试。"))
        self.refreshButton.setText(_translate("BilibiliRankWindow", "刷新数据"))
